config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'restaurants#top'
  #resourcesはやめましょう。
  #resources :restaurants
  get "restaurants" => "restaurants#index"
  post "restaurants/coordinate"
  post "restaurants/page"
  post "restaurants/search"
  #post "restaurants/coordinate"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  #改善の余地あり。１ページで完結できない為。
  def top
  end

  #周辺のレストラン情報が表示される。
  def index
    @page = 1
    #ぐるなびapi呼び出し
    restaurants_api
  end

  #検索を絞り込むためのアクション。freewordとかetc..
  def search

    #paramsで送られてきた情報をsessionに入れる。
    params.each_key{|key|
      session[key] = params[key]
      puts key
      puts session[key]
    }

    session[:offset_page] = 1
    #puts "\n\n\n\n~~~~~~~~~~~~~~~~~~~~~~~~~\n\n\n\n"
    #puts session[:offset_page]

    redirect_to restaurants_path
  end

  # ページの移動をsessionで管理
  def page
    if params[:page] == "1" then
      session[:offset_page] -= 1
    elsif params[:page] == "2" then
      session[:offset_page] += 1
    end

    redirect_to restaurants_path
  end

  #ajaxで送られてきたdataをsessionに格納
  def coordinate
    #位置情報をsessionで管理
    session[:latitude] = params[:latitude]
    session[:longitude] = params[:longitude]
    session[:offset_page] = 1

    redirect_to restaurants_path
  end

  private

  #ぐるなびapiを使って周辺情報を検索
  def restaurants_api
    require 'json'
    require 'net/https'
    require "uri"

    data = {
      "keyid": "",
      "freeword": session[:freeword],
      "input_coordinates_mode": 1,
      "latitude": session[:latitude],
      "longitude": session[:longitude],
      "range": session[:range],
      "lunch": session[:lunch],
      "no_smoking": session[:no_smoking],
      "bottomless_cup": session[:bottomless_cup],
      "buffet": session[:buffet],
      "private_room": session[:private_room],
      "e_money": session[:e_money],
      "web_reserve": session[:web_reserve],
      "parking": session[:parking],
      "birthday_privilege": session[:birthday_privilege],
      "offset_page": session[:offset_page]
    }

    query=data.to_query #ハッシュをURL文字列に変換
    uri = URI("https://api.gnavi.co.jp/RestSearchAPI/20150630/?"+query)
    #puts "\n~~~~~~~~uri~~~~~~~~\n"
    #puts uri

    begin
      response = Net::HTTP.new(uri.host, uri.port).yield_self do |http|
        http.use_ssl = true
        # 接続時に待つ最大秒数を設定
        http.open_timeout = 5
        # 読み込み一回でブロックして良い最大秒数を設定
        http.read_timeout = 30
        # Net::HTTPResponseのインスタンスが返ってくる
        http.get(uri.request_uri)
      end

      case response
      when Net::HTTPSuccess

        hash = JSON.parse(response.body, symbolize_names: true)
        @total = hash[:total_hit_count]
        @page = session[:offset_page]
        if @page.nil?
          @page = 1
          session[:offset_page] = 1
        end
        @hash = hash[:rest]

      when Net::HTTPRedirection
        logger.warn("Redirection: code=#{response.code} message=#{response.message}")
        @message = "Redirection: code=#{response.code} message=#{response.message}"
      else
        logger.error("HTTP ERROR: code=#{response.code} message=#{response.message}")
        @message = "HTTP ERROR: code=#{response.code} message=#{response.message}"
      end
    rescue IOError => e
      logger.error(e.message)
    rescue TimeoutError => e
      logger.error(e.message)
    rescue JSON::ParserError => e
      logger.error(e.message)
    rescue StandardError => e
      logger.error(e.message)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | GurunaviApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/restaurants/_search.html.slim
#searchModal.modal.fade[tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"]
  .modal-dialog[role="document"]
    .modal-content
      .modal-header
        h5#exampleModalLabel.modal-title
          | search
        button.close[type="button" data-dismiss="modal" aria-label="Close"]
          span[aria-hidden="true"]
            | ×
      .modal-body
        .container-fluid
          .row.rounded
            = form_with url: restaurants_search_path do |form|
              legend.border-bottom freeword
              .row.my-2
                = form.text_field :freeword, class: 'form-control mx-3', placeholder: '例）パスタ'

              legend.border-bottom range
              .row.mx-2
                .form-check.form-check-inline.m-3
                  = form.radio_button :range, 1, class: 'form-check-input'
                  = form.label :'300m', class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.radio_button :range, 2, class: 'form-check-input'
                  = form.label :'500m', class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.radio_button :range, 3, class: 'form-check-input'
                  = form.label :'1000m', class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.radio_button :range, 4, class: 'form-check-input'
                  = form.label :'2000m', class: 'form-check-label'

              legend.border-bottom condition
              .row.mx-2
                /!もしかしてだけどeach文で行けるのでは？
                .form-check.form-check-inline.m-3
                  = form.check_box :lunch, class: 'form-check-input'
                  = form.label :ランチ, class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.check_box :no_smoking, class: 'form-check-input'
                  = form.label :禁煙席, class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.check_box :card, class: 'form-check-input'
                  = form.label :クレジットカード, class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.check_box :bottomless_cup, class: 'form-check-input'
                  = form.label :飲み放題, class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.check_box :buffet, class: 'form-check-input'
                  = form.label :食べ放題, class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.check_box :private_room, class: 'form-check-input'
                  = form.label :個室, class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.check_box :e_money, class: 'form-check-input'
                  = form.label :電子マネー, class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.check_box :web_reserve, class: 'form-check-input'
                  = form.label :web予約, class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.check_box :parking, class: 'form-check-input'
                  = form.label :駐車場, class: 'form-check-label'
                .form-check.form-check-inline.m-3
                  = form.check_box :birthday_privilege, class: 'form-check-input'
                  = form.label :誕生日特典, class: 'form-check-label'
              .modal-footer
                button.btn.btn-secondary[type="button" data-dismiss="modal"]
                  | Close
                = form.submit :検索, class:'button btn btn-primary'

app/views/restaurants/index.html.slim
= render partial: 'search'

/! ボタン・リンククリック後に表示される画面の内容

.container-lg.mt-5
  .row
    .col-md-12

      .text-right
        button.btn.btn-primary[type="button" data-toggle="modal" data-target="#searchModal"]
          |  search
      h5
        | hit
        span.text-danger.ml-3.mr-4
          = @total
        | page
        span.text-danger.ml-3.mr-4
          = @page


      - if @hash
        - @hash.each do |rest|
          .row.p-4.border.rounded.my-4.shadow.mx-1.position-relative
            .col-md-4.text-center.m-auto
              - if rest[:image_url][:shop_image1].empty?
                /!img src="https://picsum.photos/id/1/250/250"
              - else
                = image_tag rest[:image_url][:shop_image1], class: 'rounded img-responsive img-thumbnail'

            .col-md-8.p-1.my-auto
              table.table
                  tr
                    th scope="row" name
                    td colspan="3"
                      = rest[:name]
                  tr
                    th scope="row" address
                    td
                      = rest[:address]
                  tr
                    th scope="row" opentime
                    td
                      = rest[:opentime]
                  tr
                    th scope="row" budget
                    td
                      = rest[:budget]

            /!stretched-linkの影響でmodal先がおかしくなる。position-static,relativeで解決。
            a.stretched-link.btn.position-static[data-toggle="modal" data-target="#id-#{rest[:id]}"]


            /!modaiの中身
            .modal.fade[tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true" id="id-#{rest[:id]}"]
              .modal-dialog.modal-xl.modal-dialog-centered
                .modal-content

                  .modal-header
                    h5.modal-title
                      = rest[:name]
                  .modal-body
                    .container-fluid
                      .row.rounded.mx-1.position-relative
                        .col-md-12.text-center
                          - if rest[:image_url][:shop_image1].empty?
                            /!img src="https://picsum.photos/id/1/250/250"
                          - else
                            = image_tag rest[:image_url][:shop_image1], class: 'img-fluid img-thumbnail'

                        .col-md-12.p-1
                          table.table
                              tr
                                th scope="row" address
                                td = rest[:address]
                              tr
                                th scope="row" tel
                                td = rest[:tel]
                              tr
                                th.my-auto scope="row" opentime
                                td = rest[:opentime]
                              tr
                                th scope="row" holiday
                                td = rest[:holiday]
                              tr
                                th scope="row" PR
                                td = rest[:pr][:pr_long]
                              tr
                                th scope="row" budget
                                td = rest[:budget]
                              tr
                                th scope="row" party budget
                                td = rest[:party]
                              tr
                                th scope="row" lunch budget
                                td = rest[:lunch]
                              tr
                                th scope="row" coupon
                                td
                                  a href="#{rest[:coupon_url][:mobile]}" #{rest[:coupon_url][:mobile]}
                              tr
                                th scope="row" url
                                td
                                  a href="#{rest[:url]}" #{rest[:url]}
                              tr
                                th scope="row" url_mobile
                                td
                                  a href="#{rest[:url_mobile]}" #{rest[:url_mobile]}


                  .modal-footer
                    button.btn.btn-default[type="button" data-dismiss="modal"]
                      | 閉じる

      .text-center
        - if @page == 1
          = link_to "<< prev", restaurants_page_path(page: 1), method: :post, class: 'btn btn-primary m-4 disabled'
        - else
          = link_to "<< prev", restaurants_page_path(page: 1), method: :post, class: 'btn btn-primary m-4'
        - if @page*10 >= @total then
          = link_to "next >>", restaurants_page_path(page: 2), method: :post, class: 'btn btn-primary m-4 disabled'
        - else
          = link_to "next >>", restaurants_page_path(page: 2), method: :post, class: 'btn btn-primary m-4'

script[src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"]
script[src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"]
script[src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"]

app/views/restaurants/top.html.slim

javascript:

  //(document).on('turbolinks:load', function()
  $(document).one('turbolinks:load', function() {
    if(confirm('このアプリは位置情報をつかいます。よろしいですか？')) {
      navigator.geolocation.getCurrentPosition(
        // 取得成功した場合
        function(position) {
          alert("緯度:"+position.coords.latitude+",経度"+position.coords.longitude);

          $.ajax({
            url: 'restaurants/coordinate',
            type: 'POST',
            dataType: 'json',
            async: false,
            data: {
              latitude: position.coords.latitude,
              longitude: position.coords.longitude
            },
          });

          window.location.href="restaurants/";

        },
        // 取得失敗した場合
        function(error) {
          switch(error.code) {
            case 1: //PERMISSION_DENIED
              alert("位置情報の利用が許可されていません");
              break;
            case 2: //POSITION_UNAVAILABLE
              alert("現在位置が取得できませんでした");
              break;
            case 3: //TIMEOUT
              alert("タイムアウトになりました");
              break;
            default:
              alert("その他のエラー(エラーコード:"+error.code+")");
              break;
          }
        }
      );
    }else{
      window.location.href="restaurants/";
    }
  });